export const ADMIN_GET_BLOG = 'ADMIN_GET_BLOG'
export const ADMIN_ADD_BLOG = 'ADMIN_ADD_BLOG'
export const ADMIN_UPDATE_BLOG = 'ADMIN_UPDATE_BLOG'
export const ADMIN_DELETE_BLOG = 'ADMIN_DELETE_BLOG'
